### ISSUE TITLE
Recursively update submodules

### ISSUE THREAD

**Issue by davidwinter** [jbarnette/vlad-git#11]
I have a project that has a submodule of another git repository. Within that, it has another sub-repository. When running `rake vlad:update` the first submodule is cloned correctly, however the submodule nested within isn't.

When `update` is run, it also needs the flag `--recursive`.

https://github.com/jbarnette/vlad-git/blob/master/lib/vlad/git.rb#L84

Could that line be changed to:

```
def submodule_cmd
  "#{git_cmd} submodule sync && #{git_cmd} submodule update --init --recursive"
end
```

**Comment by ktheory** [comment]
Thanks. Would you be able to submit the change as a pull request?

**Comment by ktheory** [comment]
Thanks!
