### ISSUE TITLE
git-submodule causes deploy not to work

### ISSUE THREAD

**Issue by Jasonbit** [jbarnette/vlad-git#2]
I have a non-submodule project that does not deploy correctly. Here's the error:

Neptune:myapp_rails jmint$ rake vlad:update
(in /Users/jmint/projects/myapp_rails)
Initialized empty Git repository in /home/myapp/app/myapp/scm/repo/.git/
Usage: /usr/bin/git-submodule [--quiet] [--cached] [add <repo> [-b branch]|status|init|update|summary [-n|--summary-limit <n>] [<commit>]] [--] [<path>...]
rake aborted!

If I comment out lines 21 & 38 from the lib/git.rb file, all goes well.

**Comment by jbarnette** [comment]
What version of git are you using?

**Comment by Jasonbit** [comment]
Neptune:gems jmint$ git --version
git version 1.6.4

**Comment by bhoggard** [comment]
I'm seeing the same problem with git version 1.5.4.3 and the latest releases of vlad and vlad-git.

**Comment by ethangunderson** [comment]
I'm also getting this error with 1.5.4.3.  How do you resolve this?

**Comment by bhoggard** [comment]
@ethangunderson look at the fix found in the other open issue here on github.

**Comment by ethangunderson** [comment]
@bhoggard Thanks, I ended up just updating git to 1.6.4 and it just worked.
