### ISSUE TITLE
[patch] vlad-git not compatible with with vlad 2.1.0

### ISSUE THREAD

**Issue by ktheory** [jbarnette/vlad-git#6]
The new version of vlad renamed Vlad::CommandFailedError to Rake::CommandFailedError.

This breaks the current vlad-git.

I have a patch here:
http://github.com/ktheory/vlad-git/commit/60150c379b1a0cbd9c7a68cea09a160e95443270

**Comment by jbarnette** [comment]
I'll leave this for you to close at your convenience now that you have commit .:)

**Comment by ktheory** [comment]
Fixed compatibility with Vlad 2.1.0. Closed by 6c5c815d4c62adfda48d48c710039fcc2b8393b5

Vlad::CommandFailedError => Rake::CommandFailedError
VladTestCase => Rake::TestCase
