### ISSUE TITLE
need to sync git submodules

### ISSUE THREAD

**Issue by bryanlarsen** [jbarnette/vlad-git#8]
vlad-git should run "git submodule sync" after switching branches

Here's a set of git commands you can run to illustrate the problem, which loosely corresponds to what vlad-git is trying to do:

<code>
$ git clone git://github.com/tablatom/hobocookbook.git
$ cd hobocookbook
$ git submodule update --init
$ git checkout -b hobo13doc origin/hobo13doc
$ git submodule update
fatal: reference is not a tree: 6b0840416f717e3f7607041cee31288c3ed9131a
Unable to checkout '6b0840416f717e3f7607041cee31288c3ed9131a' in submodule path 'gitorials/agility'
</code>

If you add `git submodule sync` before the last git submodule update, it works.

**Comment by ktheory** [comment]
Yup, you're right.

Would you be able to submit a patch?
